Replace DB seed with all unsigned ids (#31)
* Replace DB seed with all unsigned ids

* Add instructions how to use pwiz

* Major update of peewee model definitions

- for most ForeignKeyFields: add on_delete and on_update handlers, and
  UNSIGNED constraint required for referring to unsigned int PKs
- Base.__str__ and Size.__str__: make use of f-string syntax (and calm
  flake8 linter about binary operators at line endings)
- BaseModule
    - add defaults for title_en and include fields
    - add column names for admin_only, all_users, all_bases fields
- Box
    - declare box_id and rq_code fields as unique
- User
    - add column names for last_action, last_login, valid_first_day,
      valid_first_day fields

* Add beneficiary_is_* fields to Base model

* Fix init.sql

* Update pwd in README

* Add missing fields for Base model

* Remove UNSIGNED constraint for ForeignKeyField

- fix model unit tests. Otherwise invalid SQL is created (INTEGER NOT
  NULL UNSIGNED, instead of INTEGER UNSIGNED NOT NULL), see also
  https://github.com/coleifer/peewee/issues/1594
- remove duplicated line in test function

* Update new fields of Base model

- add separate_shop_and_warehouse_products field
- fix constraints; using default= resulted in
    pymysql.err.InternalError: (1054, "Unknown column
    'beneficiaryisregistered' in 'field list'")

* Add symlink for flask/setup.cfg in repo root

This way, pre-commit can read it for configuration of linter/formatter
tools

* Use unused QR code for box creation test

Avoid failing UNIQUE constraint when inserting new row in the Box model
(qr_code attribute; or stock.qr_id MySQL field)

* Update test data acc. to new database dump

- related to f2c5d36
- silence flake8 linter warning about line starting with binary operator
  (which is preferred by the formatter black)

Co-authored-by: Philipp Metzner <beth.aleph@yahoo.de>