Revert "build(deps-dev): bump the front-dev-minor-update group across 2 directories with 6 updates (#2834)"
This reverts commit 79df84f73370ccbcd794ca25c59d31d91e3857e2.
Issue with new rollup when building Docker image locally.

```
boxtribute-front-1  | /app/node_modules/.pnpm/rollup@4.62.3/node_modules/rollup/dist/native.js:121
boxtribute-front-1  |           throw new Error(
boxtribute-front-1  |                 ^
boxtribute-front-1  |
boxtribute-front-1  | Error: Cannot find module @rollup/rollup-linux-x64-gnu. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try `npm i` again after removing both package-lock.json and node_modules directory.
boxtribute-front-1  |     at requireWithFriendlyError (/app/node_modules/.pnpm/rollup@4.62.3/node_modules/rollup/dist/native.js:121:9)
boxtribute-front-1  |     at Object.<anonymous> (/app/node_modules/.pnpm/rollup@4.62.3/node_modules/rollup/dist/native.js:130:76)
boxtribute-front-1  |     ... 2 lines matching cause stack trace ...
boxtribute-front-1  |     at Module.load (node:internal/modules/cjs/loader:1275:32)
boxtribute-front-1  |     at Module._load (node:internal/modules/cjs/loader:1096:12)
boxtribute-front-1  |     at cjsLoader (node:internal/modules/esm/translators:298:15)
boxtribute-front-1  |     at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:240:7)
boxtribute-front-1  |     at ModuleJob.run (node:internal/modules/esm/module_job:263:25)
boxtribute-front-1  |     at async ModuleLoader.import (node:internal/modules/esm/loader:540:24) {
boxtribute-front-1  |   [cause]: Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /app/node_modules/.pnpm/@rollup+rollup-linux-x64-gnu@4.62.3/node_modules/@rollup/rollup-linux-x64-gnu/rollup.linux-x64-gnu.node)
boxtribute-front-1  |       at Module._extensions..node (node:internal/modules/cjs/loader:1651:18)
boxtribute-front-1  |       at Module.load (node:internal/modules/cjs/loader:1275:32)
boxtribute-front-1  |       at Module._load (node:internal/modules/cjs/loader:1096:12)
boxtribute-front-1  |       at Module.require (node:internal/modules/cjs/loader:1298:19)
boxtribute-front-1  |       at require (node:internal/modules/helpers:182:18)
boxtribute-front-1  |       at requireWithFriendlyError (/app/node_modules/.pnpm/rollup@4.62.3/node_modules/rollup/dist/native.js:103:10)
boxtribute-front-1  |       at Object.<anonymous> (/app/node_modules/.pnpm/rollup@4.62.3/node_modules/rollup/dist/native.js:130:76)
boxtribute-front-1  |       at Module._compile (node:internal/modules/cjs/loader:1529:14)
boxtribute-front-1  |       at Module._extensions..js (node:internal/modules/cjs/loader:1613:10)
boxtribute-front-1  |       at Module.load (node:internal/modules/cjs/loader:1275:32) {
boxtribute-front-1  |     code: 'ERR_DLOPEN_FAILED'
boxtribute-front-1  |   }
boxtribute-front-1  | }
boxtribute-front-1  |
boxtribute-front-1  | Node.js v20.19.0
boxtribute-front-1  |  ELIFECYCLE  Command failed with exit code 1.
boxtribute-front-1 exited with code 1
```